### ISSUE TITLE
The background image is enlarged in iOS.

### ISSUE THREAD

**Issue by okapixel** [themefisher/airspace-hugo#79]
Hi, teams. Thanks for the always great themes.

On iOS devices such as iPhone and iPad, the fixed background image is too enlarged to be seen. 
This is a known bug. I tried to fix it, but I couldn't. I want you to fix it.

**Comment by Somrat37** [comment]
hey there, thanks for your concern, I fixed that bug, please take a pull of the latest code.

**Comment by okapixel** [comment]
Thank you. However, this problem does not appear to be solved yet. After all, I can't see the fixed background image.
![AA44E062-95F3-4762-9306-EF2B60FF3760](https://user-images.githubusercontent.com/13287230/79825667-a2736b80-83d4-11ea-9244-308fb60a085f.jpeg)

**Comment by Somrat37** [comment]
hey there, actually you can't see this on our demo site yet. you can download the theme from github and run it on your localhost to see the fixes.

**Comment by okapixel** [comment]
Yes. I've tried the latest version of Github and it's still not fixed. I actually deployed it to Netlify, so give it a try. [Here](https://mystifying-wozniak-1f51b6.netlify.app/) 
This can only be replicated on iOS devices such as the iPhone and iPad.
![IMG_0141](https://user-images.githubusercontent.com/13287230/79830191-e4ee7580-83df-11ea-88c6-332b017740fc.png)

**Comment by Somrat37** [comment]
Is it also happening on macbook?

**Comment by okapixel** [comment]
I don't have a Mac so I don't know. However, I checked it on the actual iPad.

**Comment by Somrat37** [comment]
I don't have an iPhone or iPad, so I can't figure it out.

**Comment by gissimo** [comment]
Hi, +1 here. Issue is visible in both iPhone and iPad, but not on Macbook. I'm using latest version from GitHub.

**Comment by somrat-gyver** [comment]
Hey there, This issue has been fixed now. please download the latest code.
